# Generated by Django 6.0.6 on 2026-07-19 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, help_text='Snapshot of username at time of action (preserved even if user deleted)', max_length=150)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Failed Login'), ('PASSWORD_CHANGE', 'Password Change'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('DEACTIVATE', 'Deactivate'), ('ACTIVATE', 'Activate'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=50)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('target_model', models.CharField(blank=True, help_text="The model/table that was affected (e.g. 'Product', 'Order')", max_length=100)),
                ('target_id', models.CharField(blank=True, help_text='Primary key of the affected record', max_length=50)),
                ('extra_data', models.JSONField(blank=True, help_text='Optional JSON snapshot of before/after values', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Performed by')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor', '-timestamp'], name='accounts_au_actor_i_183206_idx'), models.Index(fields=['action', '-timestamp'], name='accounts_au_action_918219_idx'), models.Index(fields=['target_model', 'target_id'], name='accounts_au_target__e8b882_idx')],
            },
        ),
    ]
