# Generated by Django 6.0.6 on 2026-07-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_brand_logo_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentCartMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=50)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_note', models.TextField(blank=True)),
                ('items_snapshot', models.JSONField(help_text='List of {product_name, quantity , parice} at sending time')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message_text', models.TextField(help_text='Exact message sent to the shop owner')),
                ('whatsapp_url', models.URLField(blank=True, help_text='Generate click-to-chat URL')),
                ('sent_via', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='whatsapp', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
