# Generated by Django 6.0.6 on 2026-07-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_sentcartmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentcartmessage',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sentcartmessage',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='sentcartmessage',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sentcartmessage',
            name='whatsapp_url',
            field=models.URLField(blank=True, help_text='Generate click-to-chat URL', max_length=2000),
        ),
    ]
