# Generated by Django 6.0.6 on 2026-07-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_price'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_width_00cc6c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('brand', 'model_name')},
        ),
        migrations.AddField(
            model_name='product',
            name='tire_size',
            field=models.CharField(default='-', max_length=13),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='aspect_ratio',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rim_diameter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
    ]
