# Generated by Django 6.0.6 on 2026-07-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_product_catalog_pro_width_00cc6c_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='product',
            name='tire_size',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('brand', 'model_name', 'tire_size')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tire_size'], name='catalog_pro_tire_si_4fc657_idx'),
        ),
    ]
