# Generated by Django 6.0.6 on 2026-07-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['model_name'], name='catalog_pro_model_n_081eef_idx'),
        ),
    ]
